#!/bin/bash
zip=${1:-llt-simple-20181207-1305.zip}
TMPFILE=pdftest.plt
PLOTFILE=test.plt
NODES=21

YMAX1=$(./plotCBR ${zip} | awk 'BEGIN{max=0} /^[BM][dj]/ { if ($3 > max) max=$3; } END {print int(max)}')
DYMAX1=$((YMAX1 % 50))
YMAX1=$((YMAX1 - DYMAX1 + 50))

YMAX2=$(./plotCBR ${zip} | awk 'BEGIN{max=0} /^[ST][dj]/ { if ($3 > max) max=$3; } END {print int(max)}')
DYMAX2=$((YMAX2 % 50))
YMAX2=$((YMAX2 - DYMAX2 + 50))

NODES=$(./plotCBR ${zip} | tail -1 | cut '-d ' -f2)
NODES=$((NODES + 1))

echo NODES=${NODES}
echo YMAX1=${YMAX1}
echo YMAX2=${YMAX2}

if [ -z "$2" ]; then
  sed "s/@ZIPFILE@/${zip}/g
s/@YMAX1@/${YMAX1}/g
s/@YMAX2@/${YMAX2}/g
s/@NODES@/${NODES}/g
s/@TIT1@/Big-Medium/g
s/@TIT2@/Small-Tiny/g
s/@T1@/Bd1/g
s/@T2@/Bj1/g
s/@T3@/Md1/g
s/@T4@/Mj1/g
s/@T5@/Sd1/g
s/@T6@/Sj1/g
s/@T7@/Td1/g
s/@T8@/Tj1/g" ${PLOTFILE} | gnuplot -persist
else
  cat >${TMPFILE} << __EOF__
set terminal pdf
set output "$2"
__EOF__
  sed "s/@ZIPFILE@/${zip}/g
s/@YMAX1@/${YMAX1}/g
s/@YMAX2@/${YMAX2}/g
s/@NODES@/${NODES}/g
s/@TIT1@/Big-Medium/g
s/@TIT2@/Small-Tiny/g
s/@T1@/Bd1/g
s/@T2@/Bj1/g
s/@T3@/Md1/g
s/@T4@/Mj1/g
s/@T5@/Sd1/g
s/@T6@/Sj1/g
s/@T7@/Td1/g
s/@T8@/Tj1/g" ${PLOTFILE} >> ${TMPFILE}
  gnuplot ${TMPFILE}
  # rm ${TMPFILE}
fi
